on:
  push:
    branches:
      - main
jobs:
  build:
    name: update_JSON_files
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6.0.1
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: execute portfolio script
      run: |
        python update_portfolio_JSON.py
    - name: execute blog script
      run: |
        python update_blog_JSON.py

