on:
  push:
    branches:
      - main
    paths:
      - "blog_posts/**"
      - "Images/**"
permissions:
  contents: write

jobs:
  build:
    name: update_JSON_files
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6.0.1
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 # Installs beautifulsoup4, requests, etc.
    - name: execute portfolio script
      run: |
        python ./src/update_portfolio_JSON.py
    - name: execute blog script
      run: |
        python ./src/update_blog_JSON.py
    - name: Commit updated JSON
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Auto-update JSON Files" || echo "No changes to commit"
        git push

